apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tap-gui
  description: tap-gui
  tags:
    - yaml
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: tap-gui
  providesApis:
    - tap-gui-package
